### ISSUE TITLE
Refreshing a page that uses the authenticated middleware goes to login no matter what

### ISSUE THREAD

**Issue by StefanGhiban** [posva/nuxt--vuefire-example-spark-plan#1]
I have used the same middleware as you in my nuxt 3 application and whenever I refresh that page it goes automatically to login. Isnt the await supposed to not let this happen? or the firebase auth object does not reach the client in time for the user to be populated? How can I avoid this issue?

**Comment by posva** [comment]
If this works in the example, use vuefire discussions for help please.

**Comment by StefanGhiban** [comment]
That is the thing, the example doesnt work. If I refresh the page, it goes automatically to the login. It works only if I dont refresh the page, which is fine, but some users might want to refresh the page for some reason.

**Comment by posva** [comment]
I just tested locally and it works...

**Comment by StefanGhiban** [comment]
My bad, it was because I was using ssr on all pages, I just say your nuxt config and now it works fine.  Thanks
