### ISSUE TITLE
error starting projec"Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services."

### ISSUE THREAD

**Issue by czzplnm** [posva/nuxt--vuefire-example-spark-plan#2]
Checkout the repository and set it up locally and received this error.

Also tried to set up Vuefire/Firebase in my project and received the same error. 

![image](https://github.com/user-attachments/assets/ee12a6b8-7568-444b-8024-b7be38f28493)

**Comment by posva** [comment]
Use vuefire discussions for help please
